Markozy/apps/blog/urls.py
from django.conf.urls import patterns, url

import views

urlpatterns = patterns('',
                       url(r'^$', views.PostList.as_view(), name='post-list'),
                       url(r'^(?P<page>\d+)/$', views.PostList.as_view()),
                       url(r'^(?P<slug>[1-9a-z\-]+)/$', views.PostDetail.as_view(), name='post-detail'),
)

Markozy/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.views.generic import TemplateView

admin.autodiscover()

urlpatterns = patterns('',
                       url(r'^$', TemplateView.as_view(template_name='homepage.html'), name='homepage'),
                       url(r'^blog/', include('apps.blog.urls', namespace='blog')),
                       url(r'^admin/', include(admin.site.urls)),
)

Markozy/apps/blog/models.py
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.db import models
from django.template.defaultfilters import slugify


class Post(models.Model):
    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    updated_at = models.DateTimeField(auto_now=True, editable=False)
    title = models.CharField(max_length=255)
    slug = models.SlugField(max_length=255, blank=True, default='')
    content = models.TextField()
    published = models.BooleanField(default=True)
    author = models.ForeignKey(User, related_name='posts')

    def __unicode__(self):
        return self.title

    @models.permalink
    def get_absolute_url(self):
        return reverse('post-detail', kwargs={'slug': self.slug})

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(Post, self).save(*args, **kwargs)

    class Meta:
        ordering = ['-created_at', 'title']

Markozy/apps/blog/views.py
from django.views.generic import DetailView, ListView

from models import Post


class PostDetail(DetailView):
    model = Post
    template_name = 'blog/post.html'

    def get_context_data(self, **kwargs):
        context = super(PostDetail, self).get_context_data(**kwargs)
        context['post_list'] = Post.objects.filter(published=True)
        return context


class PostList(ListView):
    model = Post
    paginate_by = 5
    queryset = Post.objects.filter(published=True)
    template_name = 'blog/post_list.html'

Markozy/apps/blog/templates/blog/post.html
{% extends "base_blog.html" %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
    <div><h2>{{ post.title }}</h2></div>
    <div>{{ post.content|linebreaks }}</div>
    <div><p class="article-footer">posted by {{ post.author.first_name|capfirst }} {{ post.author.last_name|capfirst }} on {{ post.created_at }}</p></div>
{% endblock %}

Markozy/apps/blog/templates/blog/post_list.html
{% extends "base_blog.html" %}

{% block title %}Blog posts{% endblock %}

{% block content %}
    <h2>Blog Posts</h2>
    <ul>
        {% for post in post_list %}
        <li><a href="{% url 'blog:post-detail' post.slug %}">{{ post.title }}</a></li>
        {% empty %}
        <li>Sorry, no posts yet. Check back soon!</li>
        {% endfor %}
    </ul>
{% endblock %}

Markozy/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <title>Markozy | {% block title %}The home of the Markozy{% endblock %}</title>
    <link rel="stylesheet" href="{{ STATIC_URL }}base.css" type="text/css" />
</head>
<body>
    <div id="header-container">
        <div id="header">
            <h1><a href="{% url 'homepage' %}">Markozy</a></h1>
            <nav id="global-nav-bar">
                <ul>
                    <li><a href="{% url 'blog:post-list' %}">Blog</a></li>
                    <li><a href="#">Projects</a></li>
                    <li><a href="#">About Me</a></li>
                </ul>
            </nav>
        </div>
    </div>
    <div id="billboard-container">
    {% block billboard %}{% endblock %}
    </div>
    <div id="container">
        <div id="column-wrap">
            {% block columnwrap %}
            <div id="content" class="single-column">
                {% block content %}{% endblock %}
            </div>
            {% endblock %}
        </div>
    </div>
    <div id="footer">© 2013 Mark Wood</div>
</body>
</html>

Markozy/templates/base_2col.html
{% extends "base.html" %}

{% block columnwrap %}
<div id="content" class="multiple-columns">
    {% block content %}{% endblock %}
</div>
<div id="related">
    {% block related %}{% endblock %}
</div>
{% endblock %}

Markozy/templates/base_blog.html
{% extends "base_2col.html" %}

{% block billboard %}
{% endblock %}

{% block related %}
<h3>Latest blog posts</h3>
<ul>
    {% for post in post_list %}
    <li><a href="{% url 'blog:post-detail' post.slug %}">{{ post.title }}</a></li>
    {% empty %}
    <li>Sorry, no posts yet. Check back soon!</li>
    {% endfor %}
</ul>
{% endblock %}

Markozy/templates/homepage.html
{% extends "base.html" %}

{% block content %}<p>Test</p>{% endblock %}